source 'https://rubygems.org' do
  gem 'async-websocket', '~> 0.8.0'
  gem 'countries'
  gem 'credy'
  gem 'faye-websocket'
  gem 'guru_guru'
  gem 'holidays'
  gem 'net-dns'
  gem 'nokogiri'
  #gem 'passgen'
  gem 'pry'
  gem 'rotp'
  gem 'rubocop'
  gem 'rubysl-open-uri'
  gem 'shorturl'
  gem 'slack-ruby-client'
  gem 'stock_quote'
  gem 'week_of_month'
  gem 'whois-parser'
end
