source 'https://rubygems.org' do
  gem 'async-websocket'
  gem 'credy'
  gem 'easy_dice'
  gem 'faye-websocket'
  gem 'guru_guru'
  gem 'holidays'
  gem 'net-dns'
  gem 'net-ssh'
  gem 'nokogiri'
  gem 'passgen'
  gem 'rotp'
  gem 'rubysl-open-uri'
  gem 'shorturl'
  gem 'slack-ruby-client'
  gem 'stock_quote'
  gem 'week_of_month'
  gem 'whois-parser'
end
