module More
  def self.get
    ['Más doblao que chino con visitas',
  'Más hambre que el chavo',
  'Más feliz que perro con 2 colas',
  'Más prendido que tele de conserje',
  'Más raro que paco rubio',
  'Más helado que pasillo de yoghurt',
  'Más corto que muleta de cocodrilo',
  'Más lento que piropo de tartamudo',
  'Más largo que peo de culebra',
  'Más asustada que monja con atraso',
  'Más tostado que Cruz Johnson',
  'Más seco que piojo de muñeca',
  'Más inútil que bolsillo de pijama',
  'Más  seco que escupo de momia',
  'Más helado que poto de pingüino',
  'Más raro que pescado con hombros',
  'Más  asustado que pescado en Semana Santa',
  'Más puntual que novia fea',
  'Más lento que patada de astronauta',
  'Más enredado que cachipún de pulpo',
  'Más arrugado que calzoncillo de taxista',
  'Más feo que azafata del Caleuche',
  'Más ordinario que ataúd con calcomanía.',
  'Más esperado que fin de mes.',
  'Más huasqueado que perro de trineo.',
  'Más doblado que boleta de motel.',
  'Más apretado que peo de visita',
  'Más peludo que jabón de  paseo',
  'Más depilado que actor porno',
  'Más corto que beso de marido',
  'Más negro que piojo de minero',
  'Más seca que toalla de hippie',
  'Más malo que Caín ebrio',
  'Más lento que pichanga de astronauta',
  'Más rayado q puerta de perrera',
  'Más ordinario que yoyo de almejas',
  'Más falso que atún boliviano'
  ].sample
  end
end
